apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer
#  namespace: keda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-consumer
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      containers:
        - name: kafka-consumer
          image: 856727815121.dkr.ecr.us-east-1.amazonaws.com/kafka-consumer:latest
          ports:
            - containerPort: 8084
          imagePullPolicy: Always # Explicitly pull the latest image
---
apiVersion: v1
kind: Service
metadata:
  name: consumer-service
 # namespace: keda
spec:
  selector:
    app: kafka-consumer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8084
  type: LoadBalancer
